# Generated by Django 4.1.1 on 2022-09-21 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(max_length=100, verbose_name='*Tipo de Evento')),
                ('public', models.CharField(max_length=100, verbose_name='*Público-alvo')),
                ('data_evento', models.DateField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='*Foto')),
                ('local', models.CharField(max_length=100, verbose_name='*Local')),
                ('custo', models.FloatField()),
                ('descricao', models.TextField(max_length=100, verbose_name='*Descrição')),
                ('denuncia', models.IntegerField(verbose_name='Denuncia')),
                ('euvou', models.ManyToManyField(related_name='Euvou', to=settings.AUTH_USER_MODEL)),
                ('topensando', models.ManyToManyField(related_name='Topensando', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
